### ISSUE TITLE
SHA mismatch 

### ISSUE THREAD

**Issue by mrmagooey** [benswift/homebrew-extemporelinux#2]
On OSX 10.10.3 I get the following error when installing extempore from homebrew.

    > brew install extempore                                   
    ==> Installing extempore from benswift/homebrew-extempore
    ==> Downloading https://github.com/digego/extempore/archive/0.59.zip
    Error: SHA1 mismatch
    Expected: 7f73d99086f91cdee48e75e52d377feb0f3718f6
    Actual: 5795bd984399e7368d528166e18f6b71adb12b47
    Archive: /Library/Caches/Homebrew/extempore-0.59.zip
    To retry an incomplete download, remove the file above.

I have retried the download and called `shasum` to verify that the hash starting `579...` is correct for the 0.59 release zip file.

**Comment by benswift** [comment]
Should be fixed now.
